services:
  db:
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: prod_user
      POSTGRES_PASSWORD: prodsecurepassword
    # В prod мы НЕ открываем порт 5432 наружу –
    # только внутреннее подключение от pgAdmin.

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: supersecure
    # Порт 80 может быть проксирован через Traefik/Nginx, если надо