spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  application:
    name: bank-analyzer

  thymeleaf:
    cache: false

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}

  liquibase:
    enabled: true
    contexts: dev

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true