spring:
  profiles:
    active: security6

  messages:
    baseName: messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  application:
    name: bank-analyzer

  thymeleaf:
    cache: false

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}

  liquibase:
    enabled: true
    contexts: dev

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#Шаблон вывода ошибок
app:
  templates:
    error: "static/error-template.txt"


bank:
  themes:
    sber:
      primary-color: "#21a038"
      secondary-color: "#1e8a34"
      text-color: "#FFFFFF"
    tinkoff:
      primary-color: "#ffdd2d"
      secondary-color: "#fcc521"
      text-color: "#1E1E1E"
    alpha:
      primary-color: "#ef4444"
      secondary-color: "#dc2626"
      text-color: "#FFFFFF"
    vtb:
      primary-color: "#1e3a8a"
      secondary-color: "#1e40af"
      text-color: "#FFFFFF"
    default:
      primary-color: "#007bff"
      secondary-color: "#0056b3"
      text-color: "#FFFFFF"

