#url=jdbc:postgresql://localhost:5432/bank_analyze
#username=admin
#password=123456*
#changeLogFile=src/main/resources/db/changelog/db.changelog-master.yaml
#driver=org.postgresql.Driver

url=${SPRING_LIQUIBASE_URL}
username=${SPRING_LIQUIBASE_USERNAME}
password=${SPRING_LIQUIBASE_PASSWORD}
changeLogFile=${SPRING_LIQUIBASE_HANGELOGFILE}
driver=org.postgresql.Driver